(()=>{'use strict';
try{if(HTMLScriptElement.supports?.('speculationrules')){const rules=document.createElement('script');rules.type='speculationrules';rules.textContent=JSON.stringify({prefetch:[{source:'document',where:{and:[{href_matches:'/*'},{not:{selector_matches:'a[download],a[target="_blank"],[data-status="future"]'}}]},eagerness:'moderate'}]});document.head.append(rules)}}catch(_){}
const path=location.pathname.replace(/\/+$/,'/')||'/';
const plannerRoute=path.startsWith('/build-planner/')||path.startsWith('/preview/build-lab/');
const active=plannerRoute?(location.hash==='#compare'?'compare':'planner'):path.startsWith('/database/weapons/')?(location.hash==='#weapon-data-map'?'coverage':'weapons'):path==='/'?'overview':'';
const groups=[['Workspace',[['overview','OV','Overview','/'],['planner','BL','Build Planner','/build-planner/'],['compare','CP','Weapon Compare','/build-planner/#compare']]],['Database',[['weapons','WP','Weapons','/database/weapons/'],['armor','AR','Armor & Sets','/#database','future'],['mods','MD','Mods','/#database','future'],['calibrations','CA','Calibrations','/#database','future'],['deviations','DV','Deviations','/#database','future'],['cradles','CR','Cradle Overrides','/#database','future']]],['Intelligence',[['coverage','MC','Mining Coverage','/database/weapons/#weapon-data-map']]]];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=groups.map(([label,items])=>`<section class="ds-workstation-group"><span>${esc(label)}</span>${items.map(([id,icon,name,href,status])=>`<a href="${href}" aria-label="${esc(name)}"${id===active?' aria-current="page"':''}${status?` data-status="${status}"`:''}><i class="ds-workstation-icon" aria-hidden="true">${icon}</i><span>${esc(name)}</span></a>`).join('')}</section>`).join('');
document.body.classList.add('ds-workstation');
document.body.insertAdjacentHTML('afterbegin',`<button class="ds-workstation-mobile" type="button" aria-label="Open navigation" aria-expanded="false">MENU</button><div class="ds-workstation-scrim" aria-hidden="true"></div><aside class="ds-workstation-sidebar" aria-label="Dead Signal navigation"><a class="ds-workstation-brand" href="/"><span class="ds-workstation-mark" aria-hidden="true"><i></i><i></i><i></i></span><span><strong>DEAD <b>SIGNAL</b></strong><small>Once Human workstation</small></span></a><nav class="ds-workstation-nav">${nav}</nav><div class="ds-workstation-foot"><div class="ds-workstation-sizing" aria-label="Text size"><button type="button" data-ds-font-size-choice="compact" aria-label="Compact text">A-</button><button type="button" data-ds-font-size-choice="default" aria-label="Default text">A</button><button type="button" data-ds-font-size-choice="large" aria-label="Large text">A+</button><button type="button" data-ds-font-size-choice="xlarge" aria-label="Extra large text">A++</button></div><b>Miner 1.5.11</b>Player-facing data &middot; fail-closed math</div><button class="ds-workstation-collapse" type="button" aria-label="Collapse navigation" aria-expanded="true"><span aria-hidden="true">‹</span><b>Collapse</b></button></aside>`);
const button=document.querySelector('.ds-workstation-mobile');const close=()=>{document.body.classList.remove('ds-workstation-open');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open navigation')};
button.addEventListener('click',()=>{const open=document.body.classList.toggle('ds-workstation-open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close navigation':'Open navigation')});document.querySelector('.ds-workstation-scrim').addEventListener('click',close);document.querySelector('.ds-workstation-nav').addEventListener('click',event=>{if(event.target.closest('a'))close()});document.addEventListener('keydown',event=>{if(event.key==='Escape')close()});
const collapse=document.querySelector('.ds-workstation-collapse');let collapsed=false;try{collapsed=localStorage.getItem('dead-signal-nav-collapsed')==='true'}catch(_){}const setCollapsed=value=>{collapsed=value;document.body.classList.toggle('ds-workstation-collapsed',value);collapse.setAttribute('aria-expanded',String(!value));collapse.setAttribute('aria-label',value?'Expand navigation':'Collapse navigation');collapse.querySelector('span').textContent=value?'›':'‹';collapse.querySelector('b').textContent=value?'Expand':'Collapse';try{localStorage.setItem('dead-signal-nav-collapsed',String(value))}catch(_){}};setCollapsed(collapsed);requestAnimationFrame(()=>document.body.classList.add('ds-motion-ready'));collapse.addEventListener('click',()=>setCollapsed(!collapsed));
if(plannerRoute&&location.hash==='#compare')addEventListener('load',()=>setTimeout(()=>document.getElementById('compareWeaponsBtn')?.click(),0));
})();
