(()=>{'use strict';
try{if(HTMLScriptElement.supports?.('speculationrules')){const rules=document.createElement('script');rules.type='speculationrules';rules.textContent=JSON.stringify({prefetch:[{source:'document',where:{and:[{href_matches:'/*'},{not:{selector_matches:'a[download],a[target="_blank"],[data-status="future"]'}}]},eagerness:'moderate'}]});document.head.append(rules)}}catch(_){}
const path=location.pathname.replace(/\/+$/,'/')||'/';
const plannerRoute=path.startsWith('/build-planner/')||path.startsWith('/preview/build-lab/');
const active=plannerRoute?(location.hash==='#compare'?'compare':'planner'):path.startsWith('/database/weapons/')?(location.hash==='#weapon-data-map'?'coverage':'weapons'):path==='/'?'overview':'';
const groups=[['Workspace',[['overview','OV','Overview','/'],['planner','BL','Build Planner','/build-planner/'],['compare','CP','Weapon Compare','/build-planner/#compare']]],['Database',[['weapons','WP','Weapons','/database/weapons/'],['armor','AR','Armor & Sets','/#database','future'],['mods','MD','Mods','/#database','future'],['calibrations','CA','Calibrations','/#database','future'],['deviations','DV','Deviations','/#database','future'],['cradles','CR','Cradle Overrides','/#database','future']]],['Intelligence',[['coverage','MC','Mining Coverage','/database/weapons/#weapon-data-map']]]];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=groups.map(([label,items])=>`<section class="ds-workstation-group"><span>${esc(label)}</span>${items.map(([id,icon,name,href,status])=>`<a href="${href}" aria-label="${esc(name)}"${id===active?' aria-current="page"':''}${status?` data-status="${status}"`:''}><i class="ds-workstation-icon" aria-hidden="true">${icon}</i><span>${esc(name)}</span></a>`).join('')}</section>`).join('');
document.body.classList.add('ds-workstation');
document.body.insertAdjacentHTML('afterbegin',`<button class="ds-workstation-mobile" type="button" aria-label="Open navigation" aria-expanded="false">MENU</button><div class="ds-workstation-scrim" aria-hidden="true"></div><aside class="ds-workstation-sidebar" aria-label="Dead Signal navigation"><a class="ds-workstation-brand" href="/"><span class="ds-workstation-mark" aria-hidden="true"><i></i><i></i><i></i></span><span><strong>DEAD <b>SIGNAL</b></strong><small>Once Human workstation</small></span></a><nav class="ds-workstation-nav">${nav}</nav><div class="ds-workstation-foot"><div class="ds-workstation-sizing" aria-label="Text size"><button type="button" data-ds-font-size-choice="compact" aria-label="Compact text">A-</button><button type="button" data-ds-font-size-choice="default" aria-label="Default text">A</button><button type="button" data-ds-font-size-choice="large" aria-label="Large text">A+</button><button type="button" data-ds-font-size-choice="xlarge" aria-label="Extra large text">A++</button></div><b>Miner 1.5.12.9</b>Player-facing data &middot; fail-closed math</div><button class="ds-workstation-collapse" type="button" aria-label="Collapse navigation" aria-expanded="true"><span aria-hidden="true">‹</span><b>Collapse</b></button></aside>`);
const button=document.querySelector('.ds-workstation-mobile');const close=()=>{document.body.classList.remove('ds-workstation-open');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open navigation')};
button.addEventListener('click',()=>{const open=document.body.classList.toggle('ds-workstation-open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close navigation':'Open navigation')});document.querySelector('.ds-workstation-scrim').addEventListener('click',close);document.querySelector('.ds-workstation-nav').addEventListener('click',event=>{if(event.target.closest('a'))close()});document.addEventListener('keydown',event=>{if(event.key==='Escape')close()});
const collapse=document.querySelector('.ds-workstation-collapse');let collapsed=false;try{collapsed=localStorage.getItem('dead-signal-nav-collapsed')==='true'}catch(_){}const setCollapsed=value=>{collapsed=value;document.body.classList.toggle('ds-workstation-collapsed',value);collapse.setAttribute('aria-expanded',String(!value));collapse.setAttribute('aria-label',value?'Expand navigation':'Collapse navigation');collapse.querySelector('span').textContent=value?'›':'‹';collapse.querySelector('b').textContent=value?'Expand':'Collapse';try{localStorage.setItem('dead-signal-nav-collapsed',String(value))}catch(_){}};setCollapsed(collapsed);requestAnimationFrame(()=>document.body.classList.add('ds-motion-ready'));collapse.addEventListener('click',()=>setCollapsed(!collapsed));
if(plannerRoute){
 const style=document.createElement('style');style.id='ds-build-lab-semantic-color';style.textContent=`
 :root{--ds-rarity-common:#aab2b7;--ds-rarity-uncommon:#67c77a;--ds-rarity-rare:#4da3ff;--ds-rarity-epic:#b46cff;--ds-rarity-legendary:#f2b84b;--ds-evidence-proven:#59d6a3;--ds-evidence-review:#d6a85b;--ds-evidence-blocked:#e35b65;--ds-cat-weapons:#e45a55;--ds-cat-armor:#6aa7d8;--ds-cat-mods:#a66fe6;--ds-cat-cal:#d5a353;--ds-cat-deviation:#53c9a8;--ds-cat-cradle:#d45a93}
 #section-weapons{--ds-section-accent:var(--ds-cat-weapons)}#section-armor{--ds-section-accent:var(--ds-cat-armor)}#section-systems{--ds-section-accent:var(--ds-cat-deviation)}#section-plan{--ds-section-accent:var(--bl-red)}#section-notes{--ds-section-accent:#84929a}
 .bl-panel{position:relative}.bl-panel::before{content:"";position:absolute;left:-1px;top:18px;width:3px;height:44px;border-radius:0 3px 3px 0;background:var(--ds-section-accent,#37444b);opacity:.75}.bl-panel-title>b{border-color:color-mix(in srgb,var(--ds-section-accent,#e6323e) 50%,#263238);background:color-mix(in srgb,var(--ds-section-accent,#e6323e) 12%,#090d10);color:color-mix(in srgb,var(--ds-section-accent,#e6323e) 82%,white)}
 .bl-slot[data-rarity]{--ds-item-accent:var(--ds-rarity-common);border-color:color-mix(in srgb,var(--ds-item-accent) 48%,#29343b);background:radial-gradient(circle at 0 0,color-mix(in srgb,var(--ds-item-accent) 9%,transparent),transparent 42%),linear-gradient(145deg,#0c1317,#080d10);box-shadow:inset 0 1px color-mix(in srgb,var(--ds-item-accent) 12%,transparent)}
 .bl-slot[data-rarity]::after{width:45%;height:3px;background:linear-gradient(90deg,var(--ds-item-accent),transparent)}
 .bl-slot[data-rarity] .bl-item-art{border-color:color-mix(in srgb,var(--ds-item-accent) 52%,#26343a);background:radial-gradient(circle,color-mix(in srgb,var(--ds-item-accent) 18%,#10181d),#091014 72%);color:color-mix(in srgb,var(--ds-item-accent) 82%,white);box-shadow:0 0 22px color-mix(in srgb,var(--ds-item-accent) 10%,transparent)}
 .bl-slot[data-rarity] .bl-item h3{color:color-mix(in srgb,var(--ds-item-accent) 24%,#f0f3f4)}
 [data-rarity="common"]{--ds-item-accent:var(--ds-rarity-common)!important}[data-rarity="uncommon"]{--ds-item-accent:var(--ds-rarity-uncommon)!important}[data-rarity="rare"]{--ds-item-accent:var(--ds-rarity-rare)!important}[data-rarity="epic"]{--ds-item-accent:var(--ds-rarity-epic)!important}[data-rarity="legendary"]{--ds-item-accent:var(--ds-rarity-legendary)!important}
 .bl-chip[data-rarity]{border-color:color-mix(in srgb,var(--ds-item-accent) 58%,#313e45)!important;background:color-mix(in srgb,var(--ds-item-accent) 9%,#0a1115)!important;color:color-mix(in srgb,var(--ds-item-accent) 82%,white)!important}
 .bl-pick[data-rarity]{--ds-item-accent:var(--ds-rarity-common);position:relative;border-color:color-mix(in srgb,var(--ds-item-accent) 34%,#28343a)}.bl-pick[data-rarity]::before{content:"";position:absolute;left:0;top:8px;bottom:8px;width:3px;border-radius:0 3px 3px 0;background:var(--ds-item-accent);opacity:.8}.bl-pick[data-rarity]:hover:not(:disabled),.bl-pick[data-rarity]:focus-visible:not(:disabled){border-color:var(--ds-item-accent);box-shadow:0 10px 28px color-mix(in srgb,var(--ds-item-accent) 12%,rgba(0,0,0,.5));transform:translateY(-1px)}.bl-pick[data-rarity] .bl-pick-icon{border-color:color-mix(in srgb,var(--ds-item-accent) 48%,#304047);color:color-mix(in srgb,var(--ds-item-accent) 80%,white);background:color-mix(in srgb,var(--ds-item-accent) 9%,#0b1317)}
 .bl-slot[data-evidence="review"]{box-shadow:inset 0 0 0 1px rgba(214,168,91,.15)}.bl-slot[data-evidence="review"] .bl-item-note{border-left:2px solid var(--ds-evidence-review);padding-left:8px;color:#baa77f}.bl-slot[data-evidence="blocked"] .bl-item-note{border-left:2px solid var(--ds-evidence-blocked);padding-left:8px;color:#c99095}.bl-slot[data-evidence="proven"] .bl-item-note{border-left:2px solid rgba(89,214,163,.5);padding-left:8px}
 #section-systems .bl-system-card:first-child{border-top:2px solid color-mix(in srgb,var(--ds-cat-deviation) 70%,#29343b);background:linear-gradient(180deg,rgba(83,201,168,.055),#0a1014 34%)}#section-systems .bl-system-card:nth-child(2){border-top:2px solid color-mix(in srgb,var(--ds-cat-cradle) 70%,#29343b);background:linear-gradient(180deg,rgba(212,90,147,.055),#0a1014 34%)}.bl-cradle:has(strong:not(:only-child)){border-color:color-mix(in srgb,var(--ds-cat-cradle) 32%,#28343a)}
 body[data-ds-build-mode="gear"] .bl-statusbar{box-shadow:inset 0 -1px rgba(89,214,163,.08)}body[data-ds-build-mode="god"] .bl-statusbar{box-shadow:inset 0 -1px rgba(242,184,75,.13)}body[data-ds-build-mode="god"] .bl-mode button[data-mode="god"][aria-pressed="true"]{border-color:#8a5c24;background:linear-gradient(180deg,#27190b,#160e08);color:#ffd47c;box-shadow:0 0 18px rgba(242,184,75,.1)}body[data-ds-build-mode="god"] .bl-summary-mode{border-color:#8a5c24!important;color:#ffd47c!important;background:#1b1209}body[data-ds-build-mode="god"] .bl-summary-title>b{border-color:#6f5128;background:#1a130b;color:#f0bd5d}
 .bl-summary-row[data-rarity]{--ds-item-accent:var(--ds-rarity-common);padding-left:8px;border-left:2px solid color-mix(in srgb,var(--ds-item-accent) 70%,transparent)}.bl-summary-row[data-rarity] strong{color:color-mix(in srgb,var(--ds-item-accent) 28%,#e9edef)}
 @media(prefers-reduced-motion:no-preference){.bl-slot[data-rarity="legendary"]{transition:border-color .18s ease,box-shadow .22s ease,transform .18s ease}.bl-slot[data-rarity="legendary"]:hover{box-shadow:inset 0 1px rgba(242,184,75,.14),0 10px 28px rgba(242,184,75,.055)}}
 `;document.head.append(style);
 const rarityValues=new Set(['common','uncommon','rare','epic','legendary']);
 const rarityOf=node=>{const chip=[...node.querySelectorAll('.bl-chip')].find(el=>rarityValues.has(el.textContent.trim().toLowerCase()));return chip?chip.textContent.trim().toLowerCase():''};
 const evidenceOf=node=>{const value=(node.querySelector('.bl-item-note')?.textContent||'').toLowerCase();if(!value)return'';if(/unresolved|withheld|blocked|missing|unproven|unknown/.test(value))return value.includes('blocked')?'blocked':'review';return'proven'};
 const applyPlannerColor=()=>{document.querySelectorAll('.bl-slot.has-item,.bl-pick').forEach(node=>{const rarity=rarityOf(node);if(rarity){node.dataset.rarity=rarity;node.querySelectorAll('.bl-chip').forEach(chip=>{if(chip.textContent.trim().toLowerCase()===rarity)chip.dataset.rarity=rarity})}else delete node.dataset.rarity;if(node.classList.contains('bl-slot')){const evidence=evidenceOf(node);if(evidence)node.dataset.evidence=evidence;else delete node.dataset.evidence}});const rarityByName=new Map();document.querySelectorAll('.bl-slot[data-rarity] .bl-item h3').forEach(title=>rarityByName.set(title.textContent.trim(),title.closest('.bl-slot')?.dataset.rarity));document.querySelectorAll('.bl-summary-row').forEach(row=>{const name=row.querySelector('strong')?.textContent.trim();const rarity=rarityByName.get(name);if(rarity)row.dataset.rarity=rarity;else delete row.dataset.rarity});const gear=document.querySelector('.bl-mode button[data-mode="gear"]');const god=document.querySelector('.bl-mode button[data-mode="god"]');document.body.dataset.dsBuildMode=god?.getAttribute('aria-pressed')==='true'?'god':gear?.getAttribute('aria-pressed')==='true'?'gear':'gear'};
 let colorQueued=false;const queueColor=()=>{if(colorQueued)return;colorQueued=true;requestAnimationFrame(()=>{colorQueued=false;applyPlannerColor()})};new MutationObserver(queueColor).observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-pressed']});document.addEventListener('click',queueColor);addEventListener('load',queueColor);queueColor();
 }
if(plannerRoute&&location.hash==='#compare')addEventListener('load',()=>setTimeout(()=>document.getElementById('compareWeaponsBtn')?.click(),0));
})();
